# Generated by Django 5.1.3 on 2024-11-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
